export const DistrictTableDatas = [
  {
    district: "Kegeyli",
    ajs: [
      {
        id: 1,
        districtAj: "Baxram Bekbayev FX",
        grainContractPlanTon: 0,
        grainPerDayTon: 0,
        grainPerDayPercent: 0,
        grainPerSeasonTon: 0,
        grainPerSeasonPercent: 0,
        seedContractPlanTon: 0,
        seedPerDayTon: 0,
        seedPerDayPercent: 0,
        seedPerSeasonTon: 0,
        seedPerSeasonPercent: 0,
        temporarilyContractPlanTon: 0,
        temporarilyPerDayTon: 0,
        temporarilyPerDayPercent: 0,
        temporarilyPerSeasonTon: 0,
        temporarilyPerSeasonPercent: 0,
        allContractPlanTon: 0,
        allPerDayTon: 0,
        allPerDayPercent: 0,
        allPerSeasonTon: 0,
        allPerSeasonPercent: 0,
      },
      {
        id: 1,
        districtAj: "Isker Tabisker FX",
        grainContractPlanTon: 0,
        grainPerDayTon: 0,
        grainPerDayPercent: 0,
        grainPerSeasonTon: 0,
        grainPerSeasonPercent: 0,
        seedContractPlanTon: 0,
        seedPerDayTon: 0,
        seedPerDayPercent: 0,
        seedPerSeasonTon: 0,
        seedPerSeasonPercent: 0,
        temporarilyContractPlanTon: 0,
        temporarilyPerDayTon: 0,
        temporarilyPerDayPercent: 0,
        temporarilyPerSeasonTon: 0,
        temporarilyPerSeasonPercent: 0,
        allContractPlanTon: 0,
        allPerDayTon: 0,
        allPerDayPercent: 0,
        allPerSeasonTon: 0,
        allPerSeasonPercent: 0,
      },
      {
        id: 1,
        districtAj: "FX Qallibek Pirleshov",
        grainContractPlanTon: 0,
        grainPerDayTon: 0,
        grainPerDayPercent: 0,
        grainPerSeasonTon: 0,
        grainPerSeasonPercent: 0,
        seedContractPlanTon: 0,
        seedPerDayTon: 0,
        seedPerDayPercent: 0,
        seedPerSeasonTon: 0,
        seedPerSeasonPercent: 0,
        temporarilyContractPlanTon: 0,
        temporarilyPerDayTon: 0,
        temporarilyPerDayPercent: 0,
        temporarilyPerSeasonTon: 0,
        temporarilyPerSeasonPercent: 0,
        allContractPlanTon: 0,
        allPerDayTon: 0,
        allPerDayPercent: 0,
        allPerSeasonTon: 0,
        allPerSeasonPercent: 0,
      },
    ],
  },
  {
    district: "Nukus",
    ajs: [
      {
        id: 1,
        districtAj: "Agromir Gold Nukus",
        grainContractPlanTon: 0,
        grainPerDayTon: 0,
        grainPerDayPercent: 0,
        grainPerSeasonTon: 0,
        grainPerSeasonPercent: 0,
        seedContractPlanTon: 0,
        seedPerDayTon: 0,
        seedPerDayPercent: 0,
        seedPerSeasonTon: 0,
        seedPerSeasonPercent: 0,
        temporarilyContractPlanTon: 0,
        temporarilyPerDayTon: 0,
        temporarilyPerDayPercent: 0,
        temporarilyPerSeasonTon: 0,
        temporarilyPerSeasonPercent: 0,
        allContractPlanTon: 0,
        allPerDayTon: 0,
        allPerDayPercent: 0,
        allPerSeasonTon: 0,
        allPerSeasonPercent: 0,
      },
      {
        id: 1,
        districtAj: "Aqmangitli Azamat",
        grainContractPlanTon: 0,
        grainPerDayTon: 0,
        grainPerDayPercent: 0,
        grainPerSeasonTon: 0,
        grainPerSeasonPercent: 0,
        seedContractPlanTon: 0,
        seedPerDayTon: 0,
        seedPerDayPercent: 0,
        seedPerSeasonTon: 0,
        seedPerSeasonPercent: 0,
        temporarilyContractPlanTon: 0,
        temporarilyPerDayTon: 0,
        temporarilyPerDayPercent: 0,
        temporarilyPerSeasonTon: 0,
        temporarilyPerSeasonPercent: 0,
        allContractPlanTon: 0,
        allPerDayTon: 0,
        allPerDayPercent: 0,
        allPerSeasonTon: 0,
        allPerSeasonPercent: 0,
      },
    ],
  },
];
