export const RegionTableDatas = [
  {
    region: "Qoraqalpog'iston Respublikasi",
    ajs: [
      {
        aj: "Qoraqalpoqdonmahsulot",
        districts: [
          {
            district: "Kegeyli",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Nukus",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Ellikqala",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
      {
        aj: "Taxiatoshdonmahsulot",
        districts: [
          {
            district: "Amudaryo",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Taxiatosh",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Xo'jayli",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Shumanay",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Qo'nliqo'l",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
      {
        aj: "Qoraqalpoqdonmahsulot",
        districts: [
          {
            district: "Kegeyli",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Nukus",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Ellikqala",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
      {
        aj: "Taxiatoshdonmahsulot",
        districts: [
          {
            district: "Amudaryo",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Taxiatosh",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Xo'jayli",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Shumanay",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Qo'nliqo'l",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
      {
        aj: "Qoraqalpoqdonmahsulot",
        districts: [
          {
            district: "Kegeyli",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Nukus",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Ellikqala",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
      {
        aj: "Taxiatoshdonmahsulot",
        districts: [
          {
            district: "Amudaryo",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Taxiatosh",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Xo'jayli",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Shumanay",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Qo'nliqo'l",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Xorazm viloyati",
    ajs: [
      {
        aj: "Xorazmdonmahsulot",
        districts: [
          {
            district: "Urganch",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Xiva",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Farg'ona viloyati",
    ajs: [
      {
        aj: "Farg'onadonmahsulot",
        districts: [
          {
            district: "Farg'ona",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Marg'ilon",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Qo'qon",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Toshkent viloyati",
    ajs: [
      {
        aj: "Toshkentdonmahsulot",
        districts: [
          {
            district: "Chirchiq",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Angren",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Sirdaryo viloyati",
    ajs: [
      {
        aj: "Sirdaryodonmahsulot",
        districts: [
          {
            district: "Gulistan",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Surxondaryo viloyati",
    ajs: [
      {
        aj: "Surxondaryodonmahsulot",
        districts: [
          {
            district: "Termiz",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Sherobod",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Samarqand viloyati",
    ajs: [
      {
        aj: "Samarqanddonmahsulot",
        districts: [
          {
            district: "Samarqand",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Kattakurgan",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Namangan viloyati",
    ajs: [
      {
        aj: "Namangandonmahsulot",
        districts: [
          {
            district: "Namangan",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Uchqurgan",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Navoiy viloyati",
    ajs: [
      {
        aj: "Navoiydonmahsulot",
        districts: [
          {
            district: "Navoiy",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Qashqadaryo viloyati",
    ajs: [
      {
        aj: "Qashqadaryodonmahsulot",
        districts: [
          {
            district: "Qarshi",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Shahrisabz",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Kitob",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Jizzax viloyati",
    ajs: [
      {
        aj: "Jizzaxdonmahsulot",
        districts: [
          {
            district: "Jizzax",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Zarafshon",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Buxoro viloyati",
    ajs: [
      {
        aj: "Buxorodonmahsulot",
        districts: [
          {
            district: "Buxoro",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Kogon",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
  {
    region: "Andijon viloyati",
    ajs: [
      {
        aj: "Andijondonmahsulot",
        districts: [
          {
            district: "Andijon",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Asaka",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
          {
            district: "Marhamat",
            grainContractPlanTon: 0,
            grainPerDayTon: 0,
            grainPerDayPercent: 0,
            grainPerSeasonTon: 0,
            grainPerSeasonPercent: 0,
            seedContractPlanTon: 0,
            seedPerDayTon: 0,
            seedPerDayPercent: 0,
            seedPerSeasonTon: 0,
            seedPerSeasonPercent: 0,
            temporarilyContractPlanTon: 0,
            temporarilyPerDayTon: 0,
            temporarilyPerDayPercent: 0,
            temporarilyPerSeasonTon: 0,
            temporarilyPerSeasonPercent: 0,
            allContractPlanTon: 0,
            allPerDayTon: 0,
            allPerDayPercent: 0,
            allPerSeasonTon: 0,
            allPerSeasonPercent: 0,
          },
        ],
      },
    ],
  },
];
